# Generated by Django 5.0.6 on 2024-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osu_app', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Service Provider', 'Service Provider'), ('Service Taker', 'Service Taker')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True),
        ),
    ]
