# Generated by Django 5.0.6 on 2024-05-19 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osu_app', '0004_profile_user_type_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Service Provider', 'Service Provider'), ('Service Taker', 'Service Taker')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Service Provider', 'Service Provider'), ('Service Taker', 'Service Taker')], default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
