# Generated by Django 5.0.6 on 2024-05-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osu_app', '0005_alter_customuser_gender_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
