# Generated by Django 5.0.6 on 2024-05-20 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osu_app', '0007_remove_profile_gender_alter_customuser_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='SP_Profile',
        ),
        migrations.CreateModel(
            name='ST_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.jpeg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
