# Generated by Django 5.0.6 on 2024-05-20 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osu_app', '0008_rename_profile_sp_profile_st_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sp_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='st_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='st_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
