# Generated by Django 5.0.6 on 2024-10-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osu_app', '0011_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Service Provider', 'Service Provider'), ('Service Taker', 'Service Taker')], max_length=50),
        ),
    ]
